# Site settings
title: Molntjänster - Växjö Yrkeshögskola
school_term: VT 2015
author: Albert Arvidsson
email: albert.arvidsson@standout.se
description: > # this means to ignore newlines until "baseurl:"
  Den här kursen behandlar kunskaper om de affärsmässiga och tekniska
  perspektiven på molntjänster. Den studerande ska få kunskaper om hur man
  inför, driftar och styr olika molntjänster såsom Google App Engine, Amazon Web
  Services och Microsoft Azure Services Platform.
google_analytics_code: "UA-61720125-1"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://molntjanster.standout.se" # the base hostname & protocol for your site
twitter_username: albertarv
github_username:  scmx

# Build settings
markdown: kramdown

# Things to not include in _site
exclude:
  - Dockerfile
  - Gemfile
  - Gemfile.lock
  - README.md
  - bower_components
