article:          "Article"
automation:       "Automation"
baas:             "BaaS"
beta:             "Beta"
book:             "Book"
cloud:            "Cloud"
cluster:          "Cluster"
community:        "Community"
comparison:       "Comparison"
concept:          "Concept"
container:        "Container"
database:         "Database"
dbaas:            "DBaaS"
deployment:       "Deployment"
development:      "Development"
definitions:      "Definitions"
distribution:     "Distribution"
docker:           "Docker"
environment:      "Environment"
framework:        "Framework"
free:             "Free"
hosting:          "Hosting"
hypervisor:       "Hypervisor"
http:             "HTTP"
iaas:             "IaaS"
infrastructure:   "Infrastructure"
init:             "Init"
logging:          "Logging"
management:       "Management"
mongodb:          "MongoDB"
monitoring:       "Monitoring"
news:             "News"
nosql:            "NoSQL"
orchestration:    "Orchestration"
operatingsystem:  "Operating System"
opensource:       "Open Source"
paas:             "PaaS"
platform:         "Platform"
podcast:          "Podcast"
realtime:         "Realtime"
saas:             "SaaS"
scaling:          "Scaling"
security:         "Security"
sourcecode:       "Source Code"
sql:              "SQL"
sweden:           "Sweden"
versioncontrol:   "Version Control"
video:            "Video"
virtualization:   "Virtualization"
webserver:        "Webserver"
